# -*- coding: utf-8 -*-
"""CodeAlpha_Data-science_Unemployment Analysis with Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOiv0IPHfx6t1BYqmA33TVTs7f79OvOj
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style for better visuals
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

# ====================== LOAD AND CLEAN DATA ======================
# Load data
df = pd.read_csv("Unemployment.csv")

# Clean up column names by stripping whitespace
df.columns = df.columns.str.strip()

# Data cleaning
df = df.dropna()

# Rename the 'Estimated Unemployment Rate (%)' column and then select only the relevant columns
df = df.rename(columns={'Estimated Unemployment Rate (%)': 'Unemployment_Rate'})
df = df[['Date', 'Region', 'Unemployment_Rate']]

# Ensure correct data types
df['Date'] = pd.to_datetime(df['Date'])
df['Unemployment_Rate'] = pd.to_numeric(df['Unemployment_Rate'], errors='coerce')
df = df.dropna(subset=['Unemployment_Rate'])

# ====================== BASIC INFORMATION ======================
print("=== Dataset Overview ===")
print(df.head())
print("\nDataset Info:")
print(df.info())
print(f"\nTotal Records: {len(df):,}")
print(f"Date Range: {df['Date'].min()} to {df['Date'].max()}")

# ====================== OVERALL STATISTICS ======================
avg_rate = df['Unemployment_Rate'].mean()
median_rate = df['Unemployment_Rate'].median()

print(f"\nAverage Unemployment Rate: {avg_rate:.2f}%")
print(f"Median Unemployment Rate: {median_rate:.2f}%")

# ====================== VISUALIZATIONS ======================

# 1. Overall Trend
plt.figure(figsize=(14, 7))
plt.plot(df['Date'], df['Unemployment_Rate'], linewidth=1.5, alpha=0.8)
plt.title('Unemployment Rate Trend Over Time', fontsize=16, pad=20)
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 2. COVID-19 Period Analysis
covid_df = df[df['Date'] >= '2020-01-01']

plt.figure(figsize=(14, 7))
plt.plot(covid_df['Date'], covid_df['Unemployment_Rate'],
         color='red', linewidth=2)
plt.title('Unemployment Rate During COVID-19 Period', fontsize=16, pad=20)
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Monthly Seasonality
df['Month'] = df['Date'].dt.month_name()
monthly_avg = df.groupby('Month')['Unemployment_Rate'].mean().reindex(
    ['January', 'February', 'March', 'April', 'May', 'June',
     'July', 'August', 'September', 'October', 'November', 'December']
)

plt.figure(figsize=(12, 6))
monthly_avg.plot(kind='bar', color='skyblue', edgecolor='navy')
plt.title('Average Unemployment Rate by Month', fontsize=16)
plt.xlabel('Month')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# 4. Regional Analysis
region_avg = df.groupby('Region')['Unemployment_Rate'].mean().sort_values(ascending=False)

plt.figure(figsize=(14, 8))
region_avg.plot(kind='barh', color='lightcoral', edgecolor='darkred')
plt.title('Average Unemployment Rate by Region', fontsize=16)
plt.xlabel('Unemployment Rate (%)')
plt.ylabel('Region')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# Bonus: Top 5 Highest Unemployment Regions
print("\n=== Top 5 Regions with Highest Unemployment ===")
print(region_avg.head().round(2))